/**
 * Conversation affinity for browser-driven providers.
 *
 * A browser provider's history lives in the Chromium tab, not in the request.
 * Every OpenAI-style client — every coding agent — is stateless and re-sends
 * its whole message array each turn. Reconciling the two is what this module
 * does: it derives a key identifying "the conversation this tab is holding",
 * so a turn can *continue* the thread when the tab provably matches, and
 * *replay* the transcript into a fresh thread when it does not.
 *
 * Like tool-protocol.ts this is pure — no DOM, no Playwright, no HTTP — so the
 * risky logic is unit-testable without a browser.
 *
 * ## Why the key is a chain, and why it skips assistant text
 *
 * The tab's history is exactly the text wspr typed in, plus the text the model
 * generated. The client's copy of the assistant turns is a lossy re-render of
 * the latter (whitespace collapsed, fields dropped, Markdown normalized), so
 * hashing assistant *content* scores spurious misses. Assistant turns instead
 * contribute only their `tool_call` ids — wspr generates those ({@link
 * newCallId}) and a client echoes them back verbatim as `tool_call_id`.
 *
 * The key folds message-by-message, so the key of a prefix can be advanced by
 * the messages that follow it. That gives the identity the whole design rests
 * on, asserted in test/conversation.test.ts:
 *
 *     key(prefix of request N+1)  ===  key advanced after request N
 */

import { createHash } from "node:crypto";
import type { Continuity, SystemMode } from "../config.js";
import type { Message } from "./base.js";
import type { ToolCall } from "./tool-protocol.js";

/** The empty conversation — a tab that has been opened but told nothing. */
export const SEED = "wspr:v1";

/** Field separator inside a canonical line. Never appears in message text. */
const SEP = "\u001f";

function sha(input: string): string {
  return createHash("sha256").update(input).digest("hex");
}

/**
 * The canonical one-line form of a message, as it contributes to the key.
 * Roles differ in what is load-bearing:
 *
 * - `user` / `tool` — authored by the client and typed into the tab verbatim,
 *   so the content is byte-stable and fully hashed.
 * - `assistant` — generated by the tab and round-tripped through the client.
 *   Only the tool-call ids (wspr-generated, echoed verbatim) are hashed.
 * - `system` — see {@link SystemMode}; ignored by default because agents
 *   rebuild it with volatile context every turn.
 */
export function messageLine(m: Message, mode: SystemMode): string {
  switch (m.role) {
    case "user":
      return `u${SEP}${m.content ?? ""}`;
    case "tool":
      return `t${SEP}${m.tool_call_id ?? ""}${SEP}${m.name ?? ""}${SEP}${m.content ?? ""}`;
    case "assistant":
      return `a${SEP}${(m.tool_calls ?? []).map((c) => c.id).join(",")}`;
    case "system":
      return mode === "hash" ? `s${SEP}${sha(m.content ?? "").slice(0, 16)}` : `s${SEP}`;
    default:
      return `?${SEP}${(m as Message).content ?? ""}`;
  }
}

/** One fold step: the key after `m` is appended to a conversation keyed `prev`. */
export function stepKey(prev: string, m: Message, mode: SystemMode): string {
  return sha(`${prev}\u001e${messageLine(m, mode)}`);
}

/** Fold a run of messages onto a base key. */
export function foldKey(base: string, messages: Message[], mode: SystemMode): string {
  return messages.reduce((k, m) => stepKey(k, m, mode), base);
}

/**
 * The step a completed assistant turn contributes. Mirrors {@link messageLine}
 * for the assistant role, so advancing after a turn lands on exactly the key
 * the client's next request will produce for its prefix.
 */
export function assistantStep(prev: string, calls: ToolCall[]): string {
  return stepKey(prev, { role: "assistant", content: "", tool_calls: calls }, "ignore");
}

/**
 * The trailing run of messages after the last assistant message. With the
 * default `newChat: false`, this is what actually gets sent to the browser —
 * and the whole reason a tool loop works: feeding back `[user, assistant,
 * tool, tool]` sends the two `<tool_result>` blocks, not a re-ask of the stale
 * user question.
 */
export function pendingTurn(messages: Message[]): Message[] {
  for (let i = messages.length - 1; i >= 0; i--) {
    if (messages[i].role === "assistant") return messages.slice(i + 1);
  }
  return messages;
}

/** Does this turn include a user question (as opposed to only tool results)? */
export function turnContainsUser(messages: Message[]): boolean {
  return messages.some((m) => m.role === "user");
}

/** What a turn should do with the tab it was handed. */
export interface TurnPlan {
  /** `continue` types only the pending turn; `replay` opens a fresh thread. */
  mode: "continue" | "replay";
  /** The messages to flatten into the prompt. */
  promptMessages: Message[];
  /** The key to advance from once the turn completes. */
  base: string;
  /** Does this turn open a user question (⇒ restate the tool preamble)? */
  needsPreamble: boolean;
  /** The key the tab would need to hold for `continue` to be legal. */
  prefixKey: string;
}

export interface PlanArgs {
  messages: Message[];
  /** The conversation key the acquired page currently holds, if any. */
  tabKey: string | undefined;
  /** The request's `newChat` flag. */
  newChat?: boolean;
  continuity: Continuity;
  systemMode: SystemMode;
  /**
   * Does the request declare tools? A client that sends `tools` is an agent
   * client, and agent clients always re-send their full history — so for those
   * an empty prefix genuinely means "new conversation" rather than "continue
   * whatever you have". See the empty-prefix rule in {@link planTurn}.
   */
  stateless: boolean;
}

/**
 * Decide how to run this turn. Pure, so every rule below is testable without a
 * browser — which is the point, since getting these rules wrong corrupts a
 * conversation invisibly rather than failing loudly.
 */
export function planTurn(args: PlanArgs): TurnPlan {
  const { messages, tabKey, newChat, continuity, systemMode, stateless } = args;

  const turn = pendingTurn(messages);
  const prefix = messages.slice(0, messages.length - turn.length);
  const prefixKey = foldKey(SEED, prefix, systemMode);

  const replay = (): TurnPlan => ({
    mode: "replay",
    promptMessages: messages,
    base: SEED,
    needsPreamble: turnContainsUser(messages),
    prefixKey,
  });
  const cont = (): TurnPlan => ({
    mode: "continue",
    promptMessages: turn,
    base: prefixKey,
    needsPreamble: turnContainsUser(turn),
    prefixKey,
  });

  // An explicit request always wins over inference.
  if (newChat === true || continuity === "replay") return replay();
  if (continuity === "tab") return cont();

  // The tab provably holds this history — the happy path.
  if (tabKey !== undefined && tabKey === prefixKey) return cont();

  if (prefix.length === 0) {
    // No prefix: the client sent no assistant turn, so it is making no claim
    // about history. Ambiguous — either turn 1 of a new conversation, or a
    // caller deliberately leaning on the tab (the documented /chat multi-turn
    // story, docs/api.md).
    //
    // Resolve it by what the request declares rather than by guessing. A lone
    // message with no tools is the /chat case: continue, exactly as before. An
    // agent client (tools declared) is opening a session: give it a clean
    // thread so it does not inherit a stranger's conversation.
    if (!stateless && messages.length <= 1) return cont();
    // Nothing for a replay to rebuild over, and the tab is untouched anyway.
    if (tabKey === undefined) return cont();
    return replay();
  }

  // A prefix the tab does not match: the only safe move is to rebuild it.
  return replay();
}

/**
 * The key to store against the page once a turn has completed cleanly.
 *
 * Both modes converge here: a replay folds the whole transcript from SEED, a
 * continuation folds only the pending turn onto the prefix key. That the two
 * agree is the identity this design depends on.
 */
export function advanceKey(plan: TurnPlan, calls: ToolCall[], mode: SystemMode): string {
  return assistantStep(foldKey(plan.base, plan.promptMessages, mode), calls);
}
